!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.13 (r6666) - 27 Nov 2017 17:09
!
MODULE ADVECTION_MOD_DIFF
  IMPLICIT NONE
  PRIVATE 
  PUBLIC advect_1d, gridind_type
  PUBLIC advect_1d_tlm
  TYPE GRIDIND_TYPE
      REAL, ALLOCATABLE :: x(:)
      INTEGER, ALLOCATABLE :: fx(:)
      INTEGER, ALLOCATABLE :: f1x(:)
      INTEGER, ALLOCATABLE :: g1x(:)
  END TYPE GRIDIND_TYPE

CONTAINS
!  Differentiation of advect_1d in forward (tangent) mode:
!   variations   of useful results: y
!   with respect to varying inputs: u x
!   RW status of diff variables: u:in x:in y:out
  SUBROUTINE ADVECT_1D_TLM(nx, nt, x, x_tl, y, y_tl, c, dt, dx, u, u_tl&
&   , grid)
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: nx, nt
    REAL, INTENT(IN) :: c, dt, dx, u
    REAL, INTENT(IN) :: u_tl
    REAL, INTENT(IN) :: x(nx)
    REAL, INTENT(IN) :: x_tl(nx)
    REAL, INTENT(OUT) :: y(nx)
    REAL, INTENT(OUT) :: y_tl(nx)
    TYPE(GRIDIND_TYPE), INTENT(IN) :: grid
    INTEGER :: t, j
    REAL :: xold(nx), xhalf(nx)
    REAL :: xold_tl(nx), xhalf_tl(nx)
    xold_tl = x_tl
    xold = x
    xhalf_tl = 0.0
!Advect once around the domain (if u = 1)
    DO t=1,nt
      DO j=1,nx
        xhalf_tl(grid%fx(j)) = 0.5*(xold_tl(grid%fx(j))+xold_tl(grid%g1x&
&         (j))) - 0.5*c*(xold_tl(grid%fx(j))-xold_tl(grid%g1x(j)))
        xhalf(grid%fx(j)) = 0.5*(xold(grid%fx(j))+xold(grid%g1x(j))) - &
&         0.5*c*(xold(grid%fx(j))-xold(grid%g1x(j)))
      END DO
      DO j=1,nx
        xold_tl(grid%fx(j)) = xold_tl(grid%fx(j)) - dt*u_tl*(xhalf(grid%&
&         f1x(j))-xhalf(grid%fx(j)))/dx - u*dt*(xhalf_tl(grid%f1x(j))-&
&         xhalf_tl(grid%fx(j)))/dx
        xold(grid%fx(j)) = xold(grid%fx(j)) - u*dt/dx*(xhalf(grid%f1x(j)&
&         )-xhalf(grid%fx(j)))
      END DO
    END DO
    y_tl = xold_tl
    y = xold
  END SUBROUTINE ADVECT_1D_TLM
  SUBROUTINE ADVECT_1D(nx, nt, x, y, c, dt, dx, u, grid)
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: nx, nt
    REAL, INTENT(IN) :: c, dt, dx, u
    REAL, INTENT(IN) :: x(nx)
    REAL, INTENT(OUT) :: y(nx)
    TYPE(GRIDIND_TYPE), INTENT(IN) :: grid
    INTEGER :: t, j
    REAL :: xold(nx), xhalf(nx)
    xold = x
!Advect once around the domain (if u = 1)
    DO t=1,nt
      DO j=1,nx
        xhalf(grid%fx(j)) = 0.5*(xold(grid%fx(j))+xold(grid%g1x(j))) - &
&         0.5*c*(xold(grid%fx(j))-xold(grid%g1x(j)))
      END DO
      DO j=1,nx
        xold(grid%fx(j)) = xold(grid%fx(j)) - u*dt/dx*(xhalf(grid%f1x(j)&
&         )-xhalf(grid%fx(j)))
      END DO
    END DO
    y = xold
  END SUBROUTINE ADVECT_1D
END MODULE ADVECTION_MOD_DIFF
